### ISSUE TITLE
Huffman Encoding Speed

### ISSUE THREAD

**Issue by SethMichaelLarson** [python-hyper/hpack#65]
Did some benchmarks for huffman encoding and comparing the existing `HuffmanEncoder.encode()` to my own implementation I see a **71%** speed difference. My own implementation is not optimal, I am sure there are many things that could be done differently but may be a good starting point to speeding up HPACK.

I will do some additional work and take a look at what I can do to speed this part of the library up, as apparently it's a significant percentage of the cycle usage for the library.

**Comment by Lukasa** [comment]
Yup, I'd be delighted to see speedups in the Huffman encoder. In general, Huffman speedups are good. However, as we're currently piggybacking on a really great algorithm, it'd be awesome if you could publish benchmarks as you go so that we can verify the performance improvements. That way as well we can incrementally build up a collection of benchmarks that we can use to keep track of performance as time passes.

**Comment by SethMichaelLarson** [comment]
@Lukasa Of course! Perhaps I could add a "bench" directory to this repository that contains all my benchmarking tests? And I'm not suggesting that we change the decoding algorithm, it is perfectly good. I would focus my improvements on the encoding algorithm.

**Comment by Lukasa** [comment]
A bench directory would be fab. If we get far enough down the road we can consider hosting a server that stores benchmark results from Travis runs.

**Comment by SethMichaelLarson** [comment]
@Lukasa Exactly what I was thinking, but something for the future for sure! :)
